version: "3.9"

services:

    clientes_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_clientes_mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4010:4010"
      volumes:
        - ./Clientes/openapi:/aos:ro

    clientes_frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023_clientes_ui
      ports:
        - "8000:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./Clientes/openapi:/aos:ro

    logs_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_logs_mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4011:4010"
      volumes:
        - ./Logs/openapi:/aos:ro

    logs_frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023_logs_ui
      ports:
        - "8001:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./Logs/openapi:/aos:ro

    facturas_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_facturas_mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4012:4010"
      volumes:
        - ./Facturas/openapi:/aos:ro

    facturas_frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023_facturas_ui
      ports:
        - "8002:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./Facturas/openapi:/aos:ro

    notificaciones_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_notificaciones
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4013:4010"
      volumes:
        - ./Notificaciones/openapi:/aos:ro

    notificaciones_frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023_notificaciones_ui
      ports:
        - "8003:8080"
      environment:
          SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./Notificaciones/openapi:/aos:ro

    recambios_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_recambios_mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4014:4010"
      volumes:
        - ./Recambios/openapi:/aos:ro

    recambios_frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023_recambios_ui
      ports:
        - "8004:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./Recambios/openapi:/aos:ro

    trabajos_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_trabajos_mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4015:4010"
      volumes:
        - ./Trabajos/openapi:/aos:ro



    trabajos_frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023_trabajos_ui
      ports:
        - "8005:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./Trabajos/openapi:/aos:ro

    

    vehiculos_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_vehiculos_mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4016:4010"
      volumes:
        - ./Vehiculos/openapi:/aos:ro

    vehiculos_frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023_vehiculos_ui
      ports:
        - "8006:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./Vehiculos/openapi:/aos:ro
    proxy:
        image: caddy:latest
        container_name: caddy_proxy
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
        ports:
            - "80:80"
        depends_on:
            - trabajos_mock_backend
            - clientes_mock_backend
            - logs_mock_backend
            - facturas_mock_backend
            - recambios_mock_backend
            - notificaciones_mock_backend
            - vehiculos_mock_backend