version: "3"

services:
    backend:
        image: stoplight/prism:4
        container_name: mock_api
        command: mock --cors -h 0.0.0.0 "/app/openapi.yaml"
        ports:
          - "4010:4010"
        volumes:
            - ./openapi:/app:ro

    frontend:
        image: swaggerapi/swagger-ui:latest
        container_name: swagger_ui
        ports:
            - "8000:8080"
        environment:
            SWAGGER_JSON: /app/openapi.yaml
        volumes:
            - ./openapi:/app:ro

    proxy:
        image: caddy:latest
        container_name: caddy_proxy
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
        ports:
            - "80:80"
        depends_on:
            - backend