openapi: 3.0.3
info:
  version: 1.0.0
  title: AOS 2023 Grupo3 Trabajos
  description: |
    ## **[AOS 2023]** API REST para la gestión de Trabajos.
    ### Grupo 9 - Subsistema 3
    #### Licencia
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://127.0.0.1:80/api/v1
tags:
  - name: Trabajos
    description: Operaciones sobre los trabajos del taller
paths:
  /trabajos:
    $ref: paths/trabajos.yaml
  /trabajos/{idTrabajoParam}:
    $ref: paths/trabajos_{idTrabajoParam}.yaml
